# Twilio
twilio.account.sid=TWILIO_ACCOUNT_SID_AQUI
twilio.auth.token=TWILIO_AUTH_TOKEN_AQUI
twilio.number=whatsapp:+14155238886
twilio.templateSid=HX6ea4e9e9ad87d2ce2f2eae88f4c7e297
twilio.enabled=true

# Google Drive
drive.appName=ComercialValerioApp
drive.credentialsPath=credentials.json
drive.tokensDir=tokens_drive
drive.localPort=8888

# Alcances de Drive separados por comas
drive.scopes=https://www.googleapis.com/auth/drive.file

# Bus de eventos
eventBus.poolSize=4

# Configuración de la fuente de datos (HikariCP)
# Estos valores son usados por DataSourceProvider en lugar de los
# ajustes JDBC listados en persistence.xml.
db.url=jdbc:sqlserver://38.25.69.221:1433;databaseName=cv_ventas_distribucion;trustServerCertificate=true
db.employee.user=cv_employee_user
db.employee.password=Str0ngEmp!oyeeP@ssw0rd#2
db.admin.user=cv_admin_user
db.admin.password=H3ll0A$tr0ngP@ssw0rd1!
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.poolSize=10
db.maxLifetimeMs=600000

# Hash de contraseñas
password.iterations=4
password.memory=100000
password.parallelism=8

# Información de la empresa
company.name=Comercial's Valerio
company.ruc=00000000000
company.address=8W8C+52R, Piura 20210
company.phone=921 078 891
app.timezone=America/Lima
scheduler.reporteDiario.enabled=true
